var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var personHourSchema = new Schema({_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number});
var grantmakerSchema = new Schema({
	grantid: Schema.Types.ObjectId,
	userid: Schema.Types.ObjectId,
	program_name : String,
	primary_issue : String,
	number_of_grants : Number,
	amount_of_grants : Number,
	number_of_applications : Number,
	gm_invited_or_unsolicited : String,
	gm_type_of_application : String,
	gm_length_of_award : Number,
	gm_number_of_questions : Number,
	gm_site_visit : String,
	gm_loi : String,
	gm_number_of_reports : Number,
	gm_preliminary_rsch_people : [personHourSchema],
	gm_in_depth_rsch_people : [personHourSchema],
	gm_loi_requirements : [personHourSchema],
	gm_pre_loi_comm : [personHourSchema],
	gm_draft_loi : [personHourSchema],
	gm_review_loi_draft : [personHourSchema],
	gm_edit_loi : [personHourSchema],
	gm_finalize_loi : [personHourSchema],
	gm_proposal_requirements : [personHourSchema],
	gm_pre_proposal_comm : [personHourSchema],
	gm_draft_proposal : [personHourSchema],
	gm_review_proposal_draft : [personHourSchema],
	gm_edit_proposal : [personHourSchema],
	gm_finalize_proposal : [personHourSchema],
	gm_prep_visit : [personHourSchema],
	gm_site_visit : [personHourSchema],
	gm_visit_follow_ups : [personHourSchema],
	gm_letter_signing : [personHourSchema],
	gm_post_grant_comm : [personHourSchema],
	gm_report_requirements : [personHourSchema],
	gm_collect_data : [personHourSchema],
	gm_prepare_financials : [personHourSchema],
	gm_draft_report : [personHourSchema],
	gm_preview_report_draft : [personHourSchema],
	gm_edit_report : [personHourSchema],
	gm_finalize_report : [personHourSchema],
	gm_other_activity : [personHourSchema],
	rsch_issue : [personHourSchema],
	comm_prog_goals : [personHourSchema],
	program_draft_loi : [personHourSchema],
	program_finalize_loi : [personHourSchema],
	publish_loi : [personHourSchema],
	draft_rfp : [personHourSchema],
	finalize_rfp : [personHourSchema],
	publish_rfp : [personHourSchema],
	draft_report_req : [personHourSchema],
	finalize_report_req : [personHourSchema],
	publish_report_req : [personHourSchema],
	communication_with_seekers : [personHourSchema],
	field_loi_q : [personHourSchema],
	review_submitted_lois : [personHourSchema],
	ask_loi_q : [personHourSchema],
	decide_invite : [personHourSchema],
	invite_proposal : [personHourSchema],
	other_comm_loi : [personHourSchema],
	field_proposal_q : [personHourSchema],
	review_submitted_proposals : [personHourSchema],
	ask_proposal_q : [personHourSchema],
	decide_recommend : [personHourSchema],
	prep_recommendations : [personHourSchema],
	review_recommendations : [personHourSchema],
	schedule_mtg : [personHourSchema],
	hold_mtg : [personHourSchema],
	prog_schedule_visits : [personHourSchema],
	conduct_visits : [personHourSchema],
	visit_reports : [personHourSchema],
	post_visit_comm : [personHourSchema],
	declines : [personHourSchema],
	award_letters : [personHourSchema],
	accept_agreements : [personHourSchema],
	release_funds : [personHourSchema],
	post_grant_comm : [personHourSchema],
	field_report_q : [personHourSchema],
	review_submitted_reports : [personHourSchema],
	ask_report_q : [personHourSchema],
	approve_report : [personHourSchema],
	release_addl_funds : [personHourSchema],
	report_board : [personHourSchema],
	prog_other_activity : [personHourSchema],
});

module.exports = mongoose.model('maker', grantmakerSchema);
