var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var personHourSchema = new Schema({_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number});
var grantmakerSchema = new Schema({
	grantid: Schema.Types.ObjectId,
	userid: Schema.Types.ObjectId,
	program_name : String,
	primary_issue : String,
	number_of_grants : Number,
	amount_of_grants : Number,
	number_of_applications : Number,
	gm_invited_or_unsolicited : String,
	gm_type_of_application : String,
	gm_length_of_award : Number,
	gm_number_of_questions : Number,
	gm_site_visit : String,
	gm_loi : String,
	gm_number_of_reports : String,
	gm_preliminary_rsch_people : [personHourSchema],
	gm_loi_requirements : [personHourSchema],
	gm_pre_loi_comm : [personHourSchema],
	gm_draft_loi : [personHourSchema],
	gm_proposal_requirements : [personHourSchema],
	gm_pre_proposal_comm : [personHourSchema],
	gm_pre_proposal_mtg : [personHourSchema],
	gm_gather_docs : [personHourSchema],
	prepare_budget : [personHourSchema],
	gm_draft_proposal : [personHourSchema],
	gm_format_app : [personHourSchema],
	gm_proposal_other : [personHourSchema],
	gm_follow_up_qs : [personHourSchema],
	gm_site_visit : [personHourSchema],
	gm_letter_signing : [personHourSchema],
	gm_post_grant_comm : [personHourSchema],
	gm_compliance_other : [personHourSchema],
	gm_report_requirements : [personHourSchema],
	gm_collect_data : [personHourSchema],
	gm_prepare_financials : [personHourSchema],
	gm_modifications : [personHourSchema],
	gm_draft_report : [personHourSchema],
	gm_monitoring_qs : [personHourSchema],
	gm_monitoring_other : [personHourSchema],
	rsch_issue : [personHourSchema],
	comm_prog_goals : [personHourSchema],
	guidelines : [personHourSchema],
	program_loi : [personHourSchema],
	prog_proposal_req : [personHourSchema],
	field_loi_q : [personHourSchema],
	review_submitted_lois : [personHourSchema],
	decide_invite : [personHourSchema],
	invite_proposal : [personHourSchema],
	field_proposal_q : [personHourSchema],
	gm_application_other : [personHourSchema],
	review_submitted_proposals : [personHourSchema],
	due_diligence : [personHourSchema],
	ask_proposal_q : [personHourSchema],
	prog_site_visits : [personHourSchema],
	follow_up_visit : [personHourSchema],
	decide_recommend : [personHourSchema],
	schedule_mtg : [personHourSchema],
	prep_recommendations : [personHourSchema],
	hold_mtg : [personHourSchema],
	conduct_visits : [personHourSchema],
	declines_awards : [personHourSchema],
	accept_agreements : [personHourSchema],
	release_funds : [personHourSchema],
	post_grant_comm : [personHourSchema],
	gm_compliance_other : [personHourSchema],
	report_forms : [personHourSchema],
	field_report_q : [personHourSchema],
	review_submitted_reports : [personHourSchema],
	ask_report_q : [personHourSchema],
	approve_report : [personHourSchema],
	release_addl_funds : [personHourSchema],
	other_comm_reports : [personHourSchema],
	grant_mods : [personHourSchema],
	report_board : [personHourSchema],
	other_label : String,
	gm_reporting_other : [personHourSchema],
});

module.exports = mongoose.model('maker', grantmakerSchema);
