var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var grantseekerSchema = new Schema({
	grantid: Schema.Types.ObjectId,
	userid: Schema.Types.ObjectId,
	funder : String,
	past_grant : String,
	amount : Number,
	probability : Number,
	new_or_renewal : String,
	invited_or_unsolicited : String,
	type_of_support : String,
	type_of_application : String,
	length_of_award : Number,
	number_of_questions : Number,
	site_visit : String,
	loi : String,
	number_of_reports : Number,
	preliminary_rsch_people : Schema.Types.ObjectId,
	preliminary_rsch_people_hour : Number,
	in_depth_rsch_people : Schema.Types.ObjectId,
	in_depth_rsch_people_hour : Number,
	loi_requirements : Schema.Types.ObjectId,
	loi_requirements_hour : Number,
	pre_loi_comm : Schema.Types.ObjectId,
	pre_loi_comm_hour : Number,
	draft_loi : Schema.Types.ObjectId,
	draft_loi_hour : Number,
	review_loi_draft : Schema.Types.ObjectId,
	review_loi_draft_hour : Number,
	edit_loi : Schema.Types.ObjectId,
	edit_loi_hour : Number,
	finalize_loi : Schema.Types.ObjectId,
	finalize_loi_hour : Number,
	proposal_requirements : Schema.Types.ObjectId,
	proposal_requirements_hour : Number,
	pre_proposal_comm : Schema.Types.ObjectId,
	pre_proposal_comm_hour : Number,
	draft_proposal : Schema.Types.ObjectId,
	draft_proposal_hour : Number,
	review_proposal_draft : Schema.Types.ObjectId,
	review_proposal_draft_hour : Number,
	edit_proposal : Schema.Types.ObjectId,
	edit_proposal_hour : Number,
	finalize_proposal : Schema.Types.ObjectId,
	finalize_proposal_hour : Number,
	prep_visit : Schema.Types.ObjectId,
	prep_visit_hour : Number,
	site_visit : Schema.Types.ObjectId,
	site_visit_hour : Number,
	visit_follow_ups : Schema.Types.ObjectId,
	visit_follow_ups_hour : Number,
	letter_signing : Schema.Types.ObjectId,
	letter_signing_hour : Number,
	post_grant_comm : Schema.Types.ObjectId,
	post_grant_comm_hour : Number,
	report_requirements : Schema.Types.ObjectId,
	report_requirements_hour : Number,
	collect_data : Schema.Types.ObjectId,
	collect_data_hour : Number,
	prepare_financials : Schema.Types.ObjectId,
	prepare_financials_hour : Number,
	draft_report : Schema.Types.ObjectId,
	draft_report_hour : Number,
	preview_report_draft : Schema.Types.ObjectId,
	preview_report_draft_hour : Number,
	edit_report : Schema.Types.ObjectId,
	edit_report_hour : Number,
	finalize_report : Schema.Types.ObjectId,
	finalize_report_hour : Number,
	other_activity : Schema.Types.ObjectId,
	other_activity_hour : Number,
});

module.exports = mongoose.model('grant', grantseekerSchema);
