var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var personHourSchema = new Schema({_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number});
var grantseekerSchema = new Schema({
	grantid: Schema.Types.ObjectId,
	userid: Schema.Types.ObjectId,
	funder : String,
	past_grant : String,
	amount : Number,
	probability : Number,
	new_or_renewal : String,
	invited_or_unsolicited : String,
	type_of_support : String,
	type_of_application : String,
	length_of_award : Number,
	number_of_questions : Number,
	site_visit : String,
	loi : String,
	number_of_reports : Number,
	preliminary_rsch_people : [personHourSchema],
	in_depth_rsch_people : [personHourSchema],
	loi_requirements : [personHourSchema],
	pre_loi_comm : [personHourSchema],
	draft_loi : [personHourSchema],
	review_loi_draft : [personHourSchema],
	edit_loi : [personHourSchema],
	finalize_loi : [personHourSchema],
	proposal_requirements : [personHourSchema],
	pre_proposal_comm : [personHourSchema],
	draft_proposal : [personHourSchema],
	review_proposal_draft : [personHourSchema],
	edit_proposal : [personHourSchema],
	finalize_proposal : [personHourSchema],
	prep_visit : [personHourSchema],
	site_visit : [personHourSchema],
	visit_follow_ups : [personHourSchema],
	letter_signing : [personHourSchema],
	post_grant_comm : [personHourSchema],
	report_requirements : [personHourSchema],
	collect_data : [personHourSchema],
	prepare_financials : [personHourSchema],
	draft_report : [personHourSchema],
	preview_report_draft : [personHourSchema],
	edit_report : [personHourSchema],
	finalize_report : [personHourSchema],
	other_activity : [personHourSchema],
});

module.exports = mongoose.model('grant', grantseekerSchema);
