var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var grantseekerSchema = new Schema({
	grantid: Schema.Types.ObjectId,
	userid: Schema.Types.ObjectId,
	funder : String,
	past_grant : String,
	amount : Number,
	probability : Number,
	new_or_renewal : String,
	invited_or_unsolicited : String,
	type_of_support : String,
	type_of_application : String,
	length_of_award : Number,
	number_of_questions : Number,
	site_visit : String,
	loi : String,
	number_of_reports : Number,
	preliminary_rsch_people : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	in_depth_rsch_people : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	loi_requirements : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	pre_loi_comm : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	draft_loi : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	review_loi_draft : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	edit_loi : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	finalize_loi : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	proposal_requirements : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	pre_proposal_comm : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	draft_proposal : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	review_proposal_draft : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	edit_proposal : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	finalize_proposal : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	prep_visit : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	site_visit : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	visit_follow_ups : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	letter_signing : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	post_grant_comm : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	report_requirements : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	collect_data : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	prepare_financials : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	draft_report : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	preview_report_draft : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	edit_report : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	finalize_report : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
	other_activity : [{_id: Schema.Types.ObjectId, person: Schema.Types.ObjectId, hours: Number}],
});

module.exports = mongoose.model('grant', grantseekerSchema);
